### ISSUE TITLE
[Info] Python notebook using this data

### ISSUE THREAD

**Issue by morberg** [adamaltmejd/covid#11]
(Not an issue on this code base, but I don't know of any other was to communicate on github. Feel free to delete/close as you see fit.)

I have made [a simple Python notebook](https://github.com/morberg/covid-notebook) which imports this data and plots a couple of different graphs with Altair.

If you do not have a local Python environment you can run the notebook interactively [at Google Colab](https://colab.research.google.com/github/morberg/covid-notebook/blob/master/covid-lag-sweden.ipynb).

**Comment by adamaltmejd** [comment]
This is super nice, I'll add a link in the README.
