### ISSUE TITLE
deaths_lag_sweden_latest in CSV format

### ISSUE THREAD

**Issue by TropicSapling** [adamaltmejd/covid#12]
Would be nice to be able to get the exact data used to create `deaths_lag_sweden_latest.png`, perhaps in a CSV file. I found some of the data in `covid_deaths_latest.csv` but that file doesn't include your estimations. Specifically I'm most interested in the amount of deaths that occurred on each day when including the forecast of the to-be-reported deaths.

**Comment by adamaltmejd** [comment]
I'll output the predictions to a separate csv!

**Comment by TropicSapling** [comment]
Thanks :)
