### ISSUE TITLE
Add regional graphs

### ISSUE THREAD

**Issue by heatherleaf** [adamaltmejd/covid#13]
Very nice visualisation of the statistics!

How about adding some graphs for different regions? Maybe not all regions, but perhaps 

- Stockholm 
- Västra Götaland
- Skåne
- rest of Sweden

**Comment by adamaltmejd** [comment]
Would love to but the data is not available. Have asked FHM about it but so far nothing.

**Comment by morberg** [comment]
You can view total deaths (not only covid related) per region on https://morberg.github.io/covid-notebook/charts/weekly-deaths.html

Select one region by clicking in the legend on the right or on a bar in the bottom graph. Shift-click to multi-select. Click and drag in the main graph to select a time period.

**Comment by adamaltmejd** [comment]
Thats a really nice graphic! I thought the question was about deaths on actual death date (as is reported by FHM on the national level). If you just want regional total deaths, that is also available in FHM's own infographic here: https://experience.arcgis.com/experience/09f821667ce64bf7be6f9f87457ed9aa

**Comment by morberg** [comment]
I'm using data from [SCB](https://scb.se/om-scb/nyheter-och-pressmeddelanden/ingen-synlig-okning-av-antalet-doda/) who only publishes stats weekly.

I think the date is death date and not reported date based on this explanation:

> SCB:s preliminära statistik över döda har tagits fram för att ge en snabbare bild av utvecklingen under coronautbrottet, och möjlighet att jämföra med tidigare år. Statistiken redovisas helgfria måndagar och är att betrakta som rådata. Den kommer att förändras när nya uppgifter kommer in eftersom det finns en eftersläpning i inrapporteringen, särskilt för dagarna precis före publicering.
> 
> Statistik för två veckor tillbaka i tiden väntas inte förändras i någon större utsträckning. Statistiken för tidigare år baseras på SCB:s slutliga observationsregister. Endast personer med en känd dödsdag ingår i de ovanstående beräkningarna.

If it was based on reported date the historical numbers wouldn't change at all.

**Comment by adamaltmejd** [comment]
Ah right. So its not confirmed covid deaths but excess mortality. I'm planning to make a graph of excess mortality at some point. Might take some inspo from your regional division :). Thanks!

**Comment by heatherleaf** [comment]
> You can view total deaths (not only covid related) per region on https://morberg.github.io/covid-notebook/charts/weekly-deaths.html

Nice graph (but it seems dead right now). 

It would be nice to have the years overlayed - as you do in "Total by subset of counties" on https://morberg.github.io/covid-notebook/ , and still have the regions selectable. (I.e., a combination of the two graphs)

**Comment by heatherleaf** [comment]
> Ah right. So its not confirmed covid deaths but excess mortality. I'm planning to make a graph of excess mortality at some point. Might take some inspo from your regional division :). Thanks!

Looking forward to it!

**Comment by morberg** [comment]
> > You can view total deaths (not only covid related) per region on https://morberg.github.io/covid-notebook/charts/weekly-deaths.html
> 
> Nice graph (but it seems dead right now).

Sorry about that, it should work again now.
 
> It would be nice to have the years overlayed - as you do in "Total by subset of counties" on https://morberg.github.io/covid-notebook/ , and still have the regions selectable. (I.e., a combination of the two graphs)

https://morberg.github.io/covid-notebook/charts/county.html almost does this. It doesn't show the total but plots the counties individually.

**Comment by heatherleaf** [comment]
> https://morberg.github.io/covid-notebook/charts/county.html almost does this. It doesn't show the total but plots the counties individually.

Perfect! That's what I was asking for!

**Comment by heatherleaf** [comment]
> > https://morberg.github.io/covid-notebook/charts/county.html almost does this. It doesn't show the total but plots the counties individually.
> 
> Perfect! That's what I was asking for!

Minor detail, but perhaps use a N-week running average instead of yearly?

**Comment by morberg** [comment]
Here is an alternative that shows the [total number of deaths](https://morberg.github.io/covid-notebook/charts/weekly-county.html) based on counties selected.
