### ISSUE TITLE
Are you using centered moving average?

### ISSUE THREAD

**Issue by thriolsson** [adamaltmejd/covid#14]
It looks like you are using a centered moving average. I think a single sided average is better, even if it implies a lag, since it uses only data in the past and will not use the most recent data where not all deaths are reported yet.

**Comment by adamaltmejd** [comment]
Centered indeed. Single-sided are always lagged and will not follow the actual deaths. Thought this made more sense. You should think of the last 2 weeks as "not fully reported" so any moving avg will be biased. Tried to show that by including the dashed line with a moving avg+prediction (grey bars). Any suggestion for how to make that more clear?
