### ISSUE TITLE
7-day average of "By report day" is not including the most recent day for which it can be computed.

### ISSUE THREAD

**Issue by carsonwick** [adamaltmejd/covid#16]
Behavior:
7-day moving average of "By report day" time series is not displaying the most recent day for which it can be computed.

Expected Behavior:
7-day moving average of "By report day" time series should be displayed through the same date as the "By death date," and "Forecast," time series.
![image](https://user-images.githubusercontent.com/6819437/81474079-200aea00-91d1-11ea-8cd2-d06263289b5b.png)

**Comment by adamaltmejd** [comment]
Wierd... I'll look into it :)

**Comment by adamaltmejd** [comment]
Its because of when the ECDC numbers are updated. I guess I could use FHM numbers instead for the latest date but think its better to keep these separate. So it will have to be like this for now.
