### ISSUE TITLE
"By report date" line broke

### ISSUE THREAD

**Issue by bjornpiltz** [adamaltmejd/covid#25]
Since this weekend, the line "By report date" is identical to "By death date"  in your graph. (shifted by a couple of days).
This is due to how ECDC changed reporting Swedens data on 08/28. They started using FHMs internal numbers. see [here](https://github.com/owid/covid-19-data/issues/135).

If you want to keep that metric (and I think it is useful) you are going to have to calculate it yourself by subtracting yesterdays total from todays total. I hope you will, because I don't know where to find it anywhere else. Worldometer has been using the lagging metric for a while and now Our World in Data will too.

I assume ECDC decided to do this because of the 3,700 false positive PCR tests last week, but I haven't seen it communicated anywhere.

**Comment by adamaltmejd** [comment]
Removed the line for now since it wasn't really adding much.
