### ISSUE TITLE
CSV files no longer being updated

### ISSUE THREAD

**Issue by morberg** [adamaltmejd/covid#26]
It seems something broke in your [latest update](https://github.com/adamaltmejd/covid/commit/4b076a43744d0a968a088c07f9dfa414c825967c). The files [covid_deaths_latest.csv](https://github.com/adamaltmejd/covid/blob/master/data/covid_deaths_latest.csv ) and [predictions.csv](https://github.com/adamaltmejd/covid/blob/master/data/predictions.csv) are no longer being updated.

**Comment by adamaltmejd** [comment]
I think maybe it was because of the time change and the cron running 1 hr before the daily update is posted. If that was the problem its fixed now :)

**Comment by morberg** [comment]
I don’t think that is it. The files would still have been updated the following day but with one day old data.

You can also see that [your latest graph](https://github.com/adamaltmejd/covid/blob/master/docs/deaths_lag_sweden_latest.png) hasn’t been updated since October 21 in the info box on the right.

**Comment by adamaltmejd** [comment]
You were right! Think i found the problem. Lets see if it works after tomorow's update.

**Comment by morberg** [comment]
Seems to work fine now, thanks for the quick response.
