### ISSUE TITLE
Plot historical/rolling "nowcasts" for visual validation

### ISSUE THREAD

**Issue by EliasHasle** [adamaltmejd/covid#28]
The main/first plot could include a curve for the "nowcasts" that were (or _would be_, if the method has been changed) generated on each day, given the data that were accessible at that time. That way, a user could visually assess the accuracy of the model.

The way the plot appears now, with a projected steep climb in projected deaths (death reports) that contrasts extremely with the steep decline in the already reported deaths, appears too extreme to be true. It would surprise me, though not shock me, if it were indeed true. Some readers/viewers will probably discard it and never come back. A plot of historical nowcasts would place the current nowcast in a context, and if the historical nowcasts were good, a viewer would be more inclined to trust the current one. On the other hand, if the historical nowcasts showed huge biases/irregularities in certain periods (e.g. due to a less stationary process with stronger or more complex statistical dependencies than assumed), that will tell the viewer how many pinches (or truck loads) of salt he needs to take the current nowcast with. :)

**Comment by adamaltmejd** [comment]
You can find all previous predictions here if you want to make an evaluation yourself: https://github.com/adamaltmejd/covid/tree/master/docs/archive

We also evaluate the method (its the benchmark model) in this paper: https://arxiv.org/abs/2006.06840

While I think you are correct in your assessment that the current prediction is exaggerated, I don't think any more information could be fit into the plot without it becoming way to hard to read. So closing this.
