### ISSUE TITLE
Please share the link to official resources where source numbers could be taken

### ISSUE THREAD

**Issue by pitber549** [adamaltmejd/covid#7]
Great charts! Great job! 
But I have 1 question about source of data, which was used.
As I could see from code - data is taken  from url
https://www.arcgis.com/sharing/rest/content/items/b5e7488e117749c19881cce45db13f7e/data
But are there any official resources (with similar data) which could be used for verification (citing) ?

For me especially interesting is +/- fine grained death rate statistics.
I've spent a little while by googling, and I could see for example Eurostat Table [Deaths (total) by month](https://appsso.eurostat.ec.europa.eu/nui/show.do?query=BOOKMARK_DS-061474_QID_6C055B91_UID_-3F171EB0&layout=TIME,C,X,0;GEO,L,Y,0;MONTH,L,Z,0;UNIT,L,Z,1;INDICATORS,C,Z,2;&zSelection=DS-061474MONTH,M03;DS-061474INDICATORS,OBS_FLAG;DS-061474UNIT,NR;&rankName1=UNIT_1_2_-1_2)
But for some unknown reason it contains NO DATA for year 2020 (disregarding that fact that month drop-down shows only passed months of year 2020).

Also I've looked at official site http://www.statistikdatabasen.scb.se/pxweb/en/ssd/
But I could not find there any fine-grained (by time) statistics of deaths total (only yearly, no monthly, no daily ...)

So for example, from what I know, some official daily statistics for Spain could be found at 
https://www.isciii.es/QueHacemos/Servicios/VigilanciaSaludPublicaRENAVE/EnfermedadesTransmisibles/MoMo/Paginas/Informes-MoMo-2020.aspx
It is in "poor format"  (batch of pdf-s), and some charts are contradictive (has different values for the same day) - but they are official ...

So if you have some links to official resources from where one could take that timely fine-grained death-rate, it would be really great if you share them.

**Comment by pitber549** [comment]
Just to clarify, (for daily total mortality) are you using data from 
https://www.scb.se/om-scb/nyheter-och-pressmeddelanden/scb-publicerar-preliminar-statistik-over-doda-i-sverige/
https://www.scb.se/hitta-statistik/statistik-efter-amne/befolkning/befolkningens-sammansattning/befolkningsstatistik/pong/tabell-och-diagram/preliminar-statistik-over-doda/
or some other sources ?

I guess this (totals) are crucial for understanding "whole picture".
Honestly, I am quite surprised why that statistics is NOT included in table on WIKI, as a reference data (at least to aware how "big" that "covid" numbers comparing with current and historical totals ...)
https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_Sweden

**Comment by morberg** [comment]
I'm not sure what you are asking? These are the official numbers from FHM hosted on arcgis.com. You can find the link on: https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/bekraftade-fall-i-sverige/

**Comment by pitber549** [comment]
Yes, your answer is exactly what I've asked - some official link for citing (verification).
I was just thinking that if I'll make a link to that data/charts, I should have valid proof that is is official.
So link that you've gave to me provides that proof.
I guess it would be nice and helpful to mention that in in README file in the root of repository.

And just to explain my "concerns" - I was looking at about section of hosting site
https://www.esri.com/en-us/contact
and could not associate it with Sweden officials easily 😄

**Comment by pitber549** [comment]
And also what was interesting for me to understand, that according to
https://www.scb.se/hitta-statistik/statistik-efter-amne/befolkning/befolkningens-sammansattning/befolkningsstatistik/pong/tabell-och-diagram/preliminar-statistik-over-doda/
Total morality for 15 days of April 2020 is 
**4713 (2*4713 == 9426)**
While according to Eurostat Table [Deaths (total) by month](https://appsso.eurostat.ec.europa.eu/nui/show.do?query=BOOKMARK_DS-061474_QID_6C055B91_UID_-3F171EB0&layout=TIME,C,X,0;GEO,L,Y,0;MONTH,L,Z,0;UNIT,L,Z,1;INDICATORS,C,Z,2;&zSelection=DS-061474MONTH,M03;DS-061474INDICATORS,OBS_FLAG;DS-061474UNIT,NR;&rankName1=UNIT_1_2_-1_2)
Total morality for entire March 2018 is
**9437 (9437 / 2 == 4718.5)**

So it looks like in April 2020 Sweden will have **less** total deaths that in March 2018.
Maybe comparing different months is bit speculative, but still I guess it could be helpful in understanding current situation in Sweden..

**Comment by adamaltmejd** [comment]
Hi! Sorry, I'll add a readme to explain tomorrow. You can find the latest data here: https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/bekraftade-fall-i-sverige/

FHM do not archive old data, so the place to find that is here in the data folder.
