### ISSUE TITLE
add a rolling average 7 day graph, the same as FHM

### ISSUE THREAD

**Issue by SoundGoof** [adamaltmejd/covid#9]

**Comment by adamaltmejd** [comment]
Was planning to add rolling 7 day avg of reported deaths. Is that what FHM do or is their actual deaths?

**Comment by SoundGoof** [comment]
they do daliy and rolling on the same numbers, labratory confirmed covid-19 death from FHM, socialstyrelsen has numbers for all death from covid-19, if the doctor writes it in the death certificate, not just from testing, they say its about 10% more

**Comment by SoundGoof** [comment]
![avlidna per dag fhm 2020-04-29](https://user-images.githubusercontent.com/193698/80638232-69846800-8a60-11ea-8b7c-7c840c79567f.PNG)

**Comment by adamaltmejd** [comment]
Thanks! I'm thinking about it. But would maybe find it more interesting to use reported deaths. Just need to find some time to do the update .)

**Comment by adamaltmejd** [comment]
Added both a version now with three different lines. What do you think?
